services:
  mlflow:
    container_name: mlflow
    image: ghcr.io/mlflow/mlflow:v3.15.2-full
    ports:
      - "5000:5000"
    command:
      - mlflow
      - server
      - --host
      - "0.0.0.0"
      - --port
      - "5000"
      - --backend-store-uri
      - sqlite:////mlflow/data/mlflow.db
      - --artifacts-destination
      - /mlflow/data/artifacts
    volumes:
      - mlflow-data:/mlflow/data
    networks:
      - dev-network

volumes:
  mlflow-data:

networks:
  dev-network:
    external: true
