services:
  postgres:
    container_name: postgres
    image: postgres:17.10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: s3cr3t
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev-network

volumes:
  postgres-data:

networks:
  dev-network:
    external: true
